# Generated by Django 5.2.4 on 2025-08-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_num', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('cif_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('BANK', 'Bank Statement'), ('MUTUAL', 'Mutual Fund Statement'), ('CREDIT', 'Credit Card Statement'), ('LOAN', 'Loan Statement'), ('FD', 'Fixed Deposit Statement'), ('INSURANCE', 'Insurance Statement'), ('PF', 'Provident Fund Statement'), ('STOCK', 'Stock/Demat Statement'), ('BROKER', 'Brokerage Statement'), ('WALLET', 'Wallet/UPI Statement'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='FileDetails.bankdetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
    ]
