# Generated by Django 5.2.4 on 2025-08-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedetails',
            old_name='file_type',
            new_name='statement_type',
        ),
    ]
